<Project>
  <PropertyGroup>
    <Version>0.4.0</Version>
    <Version Condition="'$(AppVersion)' != ''">$(AppVersion)</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
